---
- name: Install Terminal Components
  community.general.xbps:
    pkg:
      - font-inconsolata-otf
      - rxvt-unicode
      - urxvt-perls
      - xsel
    state: present
  tags: [install_graphical_session]

- name: Install dotfiles deps
  community.general.xbps:
    pkg:
      - feh
      - tmux
    state: present
  tags: [install_graphical_session]

- name: Install Web browsers
  community.general.xbps:
    pkg:
      - firefox
    state: present
  tags: [install_graphical_session]

- name: Install development tools
  community.general.xbps:
    pkg:
      - emacs
      - git-all
    state: present
  tags: [install_graphical_session]

- name: Install Mail programs
  community.general.xbps:
    pkg:
      - gnupg2
      - pinentry-gtk
    state: present
  tags: [install_graphical_session]

- name: Install misc. programs
  community.general.xbps:
    pkg:
      - mosh
      - xlockmore
      - xscreensaver
      - pipewire
      - pavucontrol
      - wireplumber
      - dumb_runtime_dir
    state: present
  tags: [install_graphical_session]

- name: Configure PipeWire (1/2)
  ansible.builtin.file:
    path: /etc/pipewire/pipewire.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [install_graphical_session, configure_graphical_session]

- name: Configure PipeWire (2/2)
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: /etc/pipewire/pipewire.conf.d/{{ item.name }}
    state: link
  loop:
    - name: 10-wireplumber.conf
      src: /usr/share/examples/wireplumber/10-wireplumber.conf
    - name: 20-pipewire-pulse.conf
      src: /usr/share/examples/pipewire/20-pipewire-pulse.conf
  loop_control:
    label: "{{ item.name }}"
  tags: [install_graphical_session, configure_graphical_session]
