---
- name: Install dependencies
  xbps: pkg={{ item }} state=present
  with_items:
  - mongodb
  - unzip
  - openjdk

- name: Create the Unifi group
  group: name=unifi state=present

- name: Create the Unifi user
  user: name=unifi group=unifi state=present system=yes

- name: Create /opt/installfiles
  file: path=/opt/installfiles state=directory owner=root group=root mode=0755

- name: Get the Unifi Comntroller
  get_url: url=http://dl.ubnt.com/unifi/4.8.12/UniFi.unix.zip dest=/opt/installfiles/unifi.zip

- name: Expand the Unifi Archive
  unarchive: src=/opt/installfiles/unifi.zip dest=/opt copy=no creates=/opt/UniFi

- name: Fix permissions on the Unifi directory
  file: path=/opt/UniFi state=directory recurse=yes owner=unifi group=unifi

- name: Create the UniFi service
  file: path=/etc/sv/UniFi state=directory owner=root group=root mode=0755

- name: Copy the UniFi run script
  copy: src=run dest=/etc/sv/UniFi/run owner=root group=root mode=0755

- name: Enable the UniFi Service
  file: src=/etc/sv/UniFi dest=/var/service/UniFi state=link

- name: Install UniFi firewall rules
  copy: src=unifi.rules dest=/etc/iptables.d/unifi.rules owner=root group=root mode=0640
  notify:
    - iptables
