---
gw_network: 10.0.1.0
dhcp_self: 10.0.1.1
dhcp_lower: 10.0.1.2
dhcp_upper: 10.0.1.128

domain: greenhaven.michaelwashere.net
hostname: dal-gw-02

int_int: bge0
ext_int: fxp0

ntp:
- pool.ntp.org

staticHosts:
  services:
    mac: 00:1e:8c:89:78:75
    addr: 10.0.1.2
    name: GlobalDynamics
  WAP:
    mac: 04:18:d6:92:89:ae
    addr: 10.0.1.3
    name: wireless
  SIP-gateway:
    mac: 9c:ad:ef:12:32:a9
    addr: 10.0.1.4
    name: sip-gateway
  theGibson:
    mac: bc:5f:f4:7b:59:21
    addr: 10.0.1.10
    name: theGibson
  maldridgePhone:
    mac: 64:bc:0c:43:03:b9
    addr: 10.0.1.11
    name: maldridgePhone
  earth-wired:
    mac: f0:1f:af:3a:ce:a6
    addr: 10.0.1.12
    name: earth
  earth-wireless:
    mac: 70:18:8b:b9:79:87
    addr: 10.0.1.13
    name: earth
  maldridge-chromebook:
    mac: 14:2d:27:65:60:af
    addr: 10.0.1.14
    name: maldridge-chromebook
